import assert from 'node:assert/strict'
import { execFileSync } from 'node:child_process'
import { chmodSync, mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import path from 'node:path'
import test from 'node:test'

test('performance sample generator fails closed without the reviewed runtime', () => {
  const root = mkdtempSync(path.join(tmpdir(), 'viewer-performance-contract-'))
  assert.throws(
    () =>
      execFileSync('scripts/video/generate-performance-samples.sh', [root, path.join(root, 'out')], {
        encoding: 'utf8',
        stdio: 'pipe',
      }),
    /reviewed ffmpeg missing/,
  )
})

test('performance sample generator invokes only the reviewed runtime and completes samples sequentially', () => {
  const root = mkdtempSync(path.join(tmpdir(), 'viewer-performance-behavior-'))
  const runtime = path.join(root, 'ViewerVideoRuntime')
  const output = path.join(root, 'out')
  const log = path.join(root, 'runtime.log')
  mkdirSync(path.join(runtime, 'bin'), { recursive: true })
  mkdirSync(path.join(runtime, 'lib'))
  writeFileSync(path.join(runtime, 'lib', 'libmpv.2.dylib'), 'fixture')
  const ffmpeg = path.join(runtime, 'bin', 'ffmpeg')
  writeFileSync(
    ffmpeg,
    `#!/bin/bash
set -eu
output="\${!#}"
printf 'start %s\n' "$*" >> '${log}'
printf 'generated by reviewed runtime\n' > "$output"
printf 'finish %s\n' "$output" >> '${log}'
`,
  )
  chmodSync(ffmpeg, 0o755)
  const ffprobe = path.join(runtime, 'bin', 'ffprobe')
  writeFileSync(
    ffprobe,
    `#!/bin/bash
set -eu
file="\${!#}"
printf 'probe %s\n' "$file" >> '${log}'
case "$file" in
  *h264-1080p60.mp4) printf 'h264\n1920\n1080\nyuv420p\n60/1\n' ;;
  *hevc-4k30.mov) printf 'hevc\n3840\n2160\nyuv420p\n30/1\n' ;;
  *) exit 1 ;;
esac
`,
  )
  chmodSync(ffprobe, 0o755)

  execFileSync('scripts/video/generate-performance-samples.sh', [runtime, output], {
    encoding: 'utf8',
  })

  const events = readFileSync(log, 'utf8').trim().split('\n')
  assert.match(events[0], /h264_videotoolbox.*-allow_sw 0/)
  assert.match(events[0], /testsrc2=size=1920x1080:rate=60:duration=5/)
  assert.match(events[1], /finish .*h264-1080p60\.mp4/)
  assert.match(events[2], /hevc_videotoolbox.*-allow_sw 0/)
  assert.match(events[2], /testsrc2=size=3840x2160:rate=30:duration=5/)
  assert.match(events[3], /finish .*hevc-4k30\.mov/)
  assert.match(events[4], /probe .*h264-1080p60\.mp4/)
  assert.match(events[5], /probe .*hevc-4k30\.mov/)
  assert.equal(readFileSync(path.join(output, 'h264-1080p60.mp4'), 'utf8'), 'generated by reviewed runtime\n')
  assert.equal(readFileSync(path.join(output, 'hevc-4k30.mov'), 'utf8'), 'generated by reviewed runtime\n')
})
